############################################################
#
# Home Assistant Main Configuration File
#
############################################################

homeassistant:
  name: Wohnung
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 42
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include_dir_merge_named _includes/customization

http:
  api_password: !secret hass_apipassword
  trusted_networks:
    - 192.168.6.0/24
    - 127.0.0.1
  ip_ban_enabled: True

frontend:

config:

updater:

discovery:


history:
  exclude:
    domains:
      - automation
      - camera
      - group
      - sun
      - updater
      - weblink
logbook:
recorder:
  purge_days: 3
#zeroconf:
#logger:
#  default: error
#  logs:
#    homeassistant.components.sensor: info

conversation:

# Text to speech
tts:
  - platform: google
    language: 'de'
    
ifttt:
  key: bfC20Y3l7Pzsbx-h5V72L2
    
sun:


############################################################
#
# Components
#
############################################################

light:
  platform: hue
  host: 192.168.6.20
  allow_unreachable: true

tado_v1:
  username: !secret mytado_username
  password: !secret mytado_password
#  mytado_username: !secret mytado_username
#  mytado_password: !secret mytado_password

influxdb:
  host: localhost
  database: homeassistant
  username: !secret influxdb_username
  password: !secret influxdb_password
  default_measurement: state
  exclude:
    domains:
      - group
      - automation
  tags:
    instance: prod
    source: hass
  
############################################################
#
# Includes
#
############################################################

# Single Files

media_player: !include _includes/media_player.yaml
device_tracker: !include _includes/device_tracker.yaml
panel_iframe: !include _includes/panel_iframe.yaml
weblink: !include _includes/weblink.yaml
input_boolean: !include _includes/input_boolean.yaml
group: !include groups.yaml
shell_command: !include _includes/shell_commands.yaml
# Merge List

sensor: !include_dir_merge_list _includes/sensors
zone: !include_dir_merge_list _includes/zones

# Merge Named
