homeassistant:
  name: Wohnung
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 42
  unit_system: metric
  #temperature_unit: C
  time_zone: Europe/Berlin
  # Customization file
  customize: !include customize.yaml

frontend:
  extra_html_url:
    - /local/custom_ui/state-card-floorplan.html

updater:
  reporting: yes
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

conversation:

recorder:

history:

discovery:
  ignore:
    - yamaha
#  enable:
#    - homekit

config:

system_health:

mobile_app:

person:

sun:

ifttt:
  key: !secret ifttt_key

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    language: 'de'
    base_url: !secret google_translate_url

tado:
  username: !secret mytado_username
  password: !secret mytado_password

weather:
  - platform: darksky
    api_key: !secret darksky_api_key

vera:
  vera_controller_url: !secret vera_controller_url
  exclude: [ 5, 6]
  # Optional to import switches as lights - this is a list of vera device ids
  lights: [4]

mqtt:
  broker: a0d7b954-mqtt
  username: !secret mqtt_user
  password: !secret mqtt_pass
  client_id: home-assistant
  
apple_tv:
  - host: !secret apple_1_ip
    login_id: !secret apple_1_id
    credentials: !secret apple_1_key
    start_off: true

camera:
  - platform: mjpeg
    name: Die Kamera
    mjpeg_url: http://192.168.6.67/videostream.cgi?loginuse=admin&loginpas=16smiler
#    still_image_url: http://192.168.6.67/snapshot.cgi?user=admin&pwd=16smiler
    verify_ssl: false

rest_command:
  die_kamera_night_vision:
    url: 'http://192.168.6.67/camera_control.cgi?loginuse=admin&loginpas=16smiler&param=14&value={{ value }}'


alarm_control_panel: !include includes/alarm.yaml

input_boolean: !include includes/input_boolean.yaml
#input_select: !include includes/input_select.yaml
#panel_iframe: !include includes/panel_iframe.yaml
panel_custom: !include includes/panel_custom.yaml
device_tracker: !include includes/device_tracker.yaml

sensor: !include_dir_merge_list includes/sensors
binary_sensor: !include_dir_merge_list includes/binary
zone: !include_dir_merge_list includes/zones
switch: !include_dir_merge_list includes/switches

media_player: !include_dir_merge_list includes/mediaplayer

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
