- platform: template
  sensors:

############################################################
#
# Set brightness depending on Time of Day
#
############################################################

    time_brightness:
      value_template: >-
        {%- if now().strftime('%H%M')|int < 600 -%}
          64
        {%- elif now().strftime('%H%M')|int < 700 -%}
          128
        {%- elif now().strftime('%H%M')|int < 800 -%}
          192
        {%- elif now().strftime('%H%M')|int < 2000 -%}
          255
        {%- elif now().strftime('%H%M')|int < 2100 -%}
          192
        {%- elif now().strftime('%H%M')|int < 2200 -%}
          128
        {%- else -%}
          64
        {%- endif -%}

        
############################################################
#
# Show Devices as Online or Offline 
#
############################################################

    fabians_notebook:
      friendly_name: Fabians MacBook 
      value_template: "{{ 'online' if is_state('device_tracker.dasmalgadeybook', 'home') else 'offline' }}"

    leas_notebook:
      friendly_name: Leas Notebook
      value_template: "{{ 'online' if is_state('device_tracker.desktop2436t3f', 'home') else 'offline' }}"

    wolfgangs_notebook:
      friendly_name: Wolfgangs MacBook
      value_template: "{{ 'online' if is_state('device_tracker.wmbook', 'home') else 'offline' }}"

    router:
      friendly_name: Router 
      value_template: "{{ 'online' if is_state('device_tracker.gateway', 'home') else 'offline' }}"

    tado_bridge:
      friendly_name: Tado bridge 
      value_template: "{{ 'online' if is_state('device_tracker.tado', 'home') else 'offline' }}"

    tado_bridge_status:
      friendly_name: Tado bridge Status
      value_template: "{{ 'connected' if is_state('sensor.die_wohnung_tado_bridge_status', 'True') else 'disconnected' }}"

    hue_bridge:
      friendly_name: Hue bridge
      value_template: "{{ 'online' if is_state('device_tracker.ourhue', 'home') else 'offline' }}"

    raspberrypi:
      friendly_name: Raspberry Pi
      value_template: "{{ 'online' if is_state('device_tracker.raspberrypi', 'home') else 'offline' }}"      
    