default_view:
  view: yes
  icon: mdi:home
  entities:
    - updater.updater
    - device_tracker.wmphone
    - device_tracker.heikesiphone
    - device_tracker.leasiphone
    - device_tracker.androidd7e9cde22f4c3620
    - group.security

Security:
  - input_boolean.visitor